apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-api
  labels:
    app.kubernetes.io/name: grade-submission-api
    app.kubernetes.io/env: frontend
    app.kubernetes.io/instance: work-test
spec:
  containers:
  - name: grade-submission-api
    image: rslim087/kubernetes-course-grade-submission-api
    resources:
      requests: 
        memory: "128Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
