apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-portal
  namespace:  grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: grade-submission-portal
      app.kubernetes.io/env: frontend
      app.kubernetes.io/instance: work-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission-portal
        app.kubernetes.io/env: frontend
        app.kubernetes.io/instance: work-test
    spec:
      containers:
        - name: grade-submission-portal
          image: rslim087/kubernetes-course-grade-submission-portal
          env:
            - name: GRADE_SERVICE_HOST
              value: grade-submission-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5001