apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal
  labels:
    app_name: grade-submission-portal
    env: test
spec: 
  containers:
  - name: grade-submission-portal
    image: rslim087/kubernetes-course-grade-submission-portal
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
    ports:
      - containerPort: 5000

  - name: grade-submission-portal-health-checker
    image: rslim087/kubernetes-course-grade-submission-portal-health-checker
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"


# we access the pod using pod port-forwarding see the command
#  kubectl port-forward <podname> desired port:runing port
#  kubectl port-forward grade-submission-portal 8080:5000